# -*- coding: utf-8 -*-
"""Aula 01 - Introdução PNL.ipynb

Automatically generated by Colab.

Original file is located at Google Colab
    
"""

!pip install nltk

import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

nltk.download('punkt_tab')

nltk.download('punkt')

texto = "O Processamento de Linguagem Natural é Incrível! Usando nltk! Com a biblioteca nltk é possível gerenciar texto e retorná-lo em tokens!"

#Tokenização de Palavras a Partir da Informação
palavras = word_tokenize(texto)

print(palavras)

# Tokenização de Frases Completas
frases = sent_tokenize(texto)
print(frases)