# -*- coding: utf-8 -*-
"""IAAM_Aula_%5.ipynb

Automatically generated by Colab.

Original file is located at Google Colab
"""

import numpy as np
import nltk
import re
from sklearn.feature_extraction.text import CountVectorizer # Bag of Words
from sklearn.feature_selection import chi2

nltk.download('stopwords')
stopWordsPT = nltk.corpus.stopwords.words('portuguese')
# print(stopWordsPT)

frases = [
    "Eu adorei o filme, foi incrível!",  # Positivo
    "O atendimento foi horrível e demorado!",  # Negativo
    "Gostei muito da experiência, voltarei!",  # Positivo
    "O produto é de péssima qualidade!",  # Negativo
    "O filme foi péssimo e decepcionante!",  # Negativo
    "Excelente experiência, maravilhoso!",  # Positivo
    "O pior serviço que já tive!",  # Negativo
    "A comida estava deliciosa!",  # Positivo
]

labels = [1, 0, 1, 0, 0, 1, 0, 1]  # 1 = Positivo, 0 = Negativo

vectorizer = CountVectorizer(stop_words=stopWordsPT)
X = vectorizer.fit_transform(frases)
vocabulario = vectorizer.get_feature_names_out()
# print(vocabulario)
# print(X.toarray())

chi2_scores, _ = chi2(X, labels)
# print(chi2_scores)
top_n = 10 # As 10 mais Relevantes
selected_words = np.array(vocabulario)[np.argsort(chi2_scores)[-top_n:]]
print(selected_words)

positivas = set()
negativas = set()

for word in selected_words:
  indices_palavras = np.where(X[:, vocabulario.tolist().index(word)].toarray() >0)[0]
  media_label = np.mean([labels[idx] for idx in indices_palavras])
  if media_label > 0.5:
    positivas.add(word)
  else:
    negativas.add(word)

print(f"Positivas: {positivas}")
print(f"Negativas: {negativas}")

def PreProcessarTexto(texto):
  return re.findall(r'\b\w+\b', texto.lower())
print(PreProcessarTexto("O rato roeu a roupa do Imperador de Roma"))

def analisarSentimento(texto):
  tokens = PreProcessarTexto(texto)

  score = sum(1 for word in tokens if word in positivas)
  score -= sum(1 for word in tokens if word in negativas)

  if score > 0:
    return "Positivo"
  elif score < 0:
    return "Negativo"
  else:
    return "Neutro"

print(analisarSentimento("O rato roeu a roupa do Imperador de Roma"))