# -*- coding: utf-8 -*-
"""IAAM, Analise_Sintatica.ipynb

Automatically generated by Colab.

Original file is located at Google Colab

# O que é Análise Sintática?

A Análise Sintática (ou parsing) consiste em identificar a estrutura gramatical de uma frase, ou seja, entender como as palavras se organizam e se relacionam. Em chatbots, isso é essencial para interpretar corretamente as intenções do usuário e extrair entidades importantes.

Por exemplo, na frase:

> "Quero reservar um hotel em São Paulo para amanhã"

A análise sintática ajuda o chatbot a identificar:

- Verbo principal: "reservar"
- Objeto direto: "um hotel"
- Complemento de lugar: "em São Paulo"
- Complemento de tempo: "para amanhã"

## Por que é importante em chatbots?
- Identificar intenção (ex: reservar, perguntar, cancelar)
- Extrair entidades (ex: datas, locais, nomes)
- Compreender contexto gramatical para evitar confusões
"""

!pip install -U spacy
!python -m spacy download pt_core_news_sm

import spacy

# Carregando o modelo de português
nlp = spacy.load("pt_core_news_sm")

# Frase simulando entrada do usuário no chatbot
frase = "Gostaria de agendar uma consulta com o doutor João amanhã às 15 horas."

# Processar a frase
doc = nlp(frase)

# Exibir análise sintática
print(f"{'Token':<15}{'Posição':<10}{'Tipo':<10}{'Dependência':<15}{'Palavra Pai':<15}")
print("="*70)
for token in doc:
    print(f"{token.text:<15}{token.i:<10}{token.pos_:<10}{token.dep_:<15}{token.head.text:<15}")

"""| POS tag (`token.pos_`) | Descrição                        | Exemplo em inglês           |
|------------------------|----------------------------------|-----------------------------|
| `ADJ`                  | Adjetivo                         | *happy, large, round*       |
| `ADP`                  | Preposição ou pósposição         | *in, on, under*             |
| `ADV`                  | Advérbio                         | *quickly, never, very*      |
| `AUX`                  | Verbo auxiliar                   | *is, have, do*              |
| `CONJ`                 | Conjunção                        | *and, but* (pouco usado)    |
| `CCONJ`                | Conjunção coordenativa           | *and, or, but*              |
| `SCONJ`                | Conjunção subordinativa          | *because, if, when*         |
| `DET`                  | Determinante                     | *the, a, an, some*          |
| `INTJ`                 | Interjeição                      | *wow, oops, hello*          |
| `NOUN`                 | Substantivo comum                | *dog, car, computer*        |
| `PROPN`                | Substantivo próprio              | *Alice, London, Google*     |
| `NUM`                  | Número                           | *one, 2, third*             |
| `PART`                 | Partícula (ex: “to” de infinitivo)| *to, 's, not*               |
| `PRON`                 | Pronome                          | *he, she, it, they*         |
| `PUNCT`                | Pontuação                        | *., !, ?*                   |
| `SYM`                  | Símbolo                          | *$, %, ©*                   |
| `VERB`                 | Verbo principal                  | *run, eat, think*           |
| `X`                    | Outro / desconhecido             | caracteres estranhos        |
| `SPACE`                | Espaço em branco                 |                             |

## 1. **Identificar a Intenção Baseada no Verbo Raiz (`ROOT`)**

### Conceito:
O verbo principal da frase normalmente está ligado à ação que o usuário quer realizar. Em `spaCy`, ele aparece como o **token com dependência `ROOT`**.

### Exemplo:
Frase:  
> **"Gostaria de agendar uma consulta com o doutor João amanhã às 15 horas."**

Verbo raiz:
```python
for token in doc:
    if token.dep_ == "ROOT":
        print(f"Verbo principal (intenção): {token.text}")
```

💬 Saída:
```
Verbo principal (intenção): Gostaria
```

> **Regra**: Se o verbo raiz for “gostaria”, “quero”, “preciso”, “marcar” → intenção provável é **agendar**.

## 2. **Identificar Nomes Próprios (ex: "João")**

### Conceito:
Nomes próprios são classificados como `PROPN` (Proper Noun). São úteis para descobrir **com quem** a ação está sendo realizada (ex: médico, professor, cliente).

### Exemplo:
```python
nomes = [token.text for token in doc if token.pos_ == "PROPN"]
print("Nomes próprios detectados:", nomes)
```

Saída:
```
Nomes próprios detectados: ['João']
```

> **Regra**: Combine com o substantivo anterior (“doutor”, “professor”, etc.) para criar uma entidade: **“doutor João”**.

## 3. **Extrair Datas e Horários**

### Conceito:
Datas e horários podem ser:
- Advérbios de tempo: `amanhã`, `hoje`, `depois`
- Números com substantivos como "horas": `15 horas`
- Preposições: `às 15 horas`, `em 10 de abril`, etc.

### Exemplo:
```python
datas = []
horarios = []

for i, token in enumerate(doc):
    # Data por advérbio
    if token.text.lower() in ["hoje", "amanhã", "depois"]:
        datas.append(token.text)

    # Horário com número + "horas"
    if token.like_num and i+1 < len(doc) and doc[i+1].text.lower() == "horas":
        horarios.append(f"{token.text} {doc[i+1].text}")

print("Datas detectadas:", datas)
print("Horários detectados:", horarios)
```

Saída:
```
Datas detectadas: ['amanhã']
Horários detectados: ['15 horas']
```

> **Regra**: Agrupar essas informações como parte dos **slots** da intenção.

## Exemplo
"""

import spacy

nlp = spacy.load("pt_core_news_sm")
frase = "Gostaria de agendar uma consulta com o doutor João amanhã às 24 horas."
doc = nlp(frase)

intencao = ""
nome = ""
data = ""
hora = ""

# 1. Intenção
for token in doc:
    if token.dep_ == "ROOT":
        intencao = token.text.lower()

# 2. Nome próprio
nomes_proprios = [token.text for token in doc if token.pos_ == "PROPN"]

# 3. Data e Hora
for i, token in enumerate(doc):
    if token.text.lower() in ["hoje", "amanhã", "depois"]:
        data = token.text
    if token.like_num and i+1 < len(doc) and doc[i+1].text.lower() == "horas":
        hora = f"{token.text} {doc[i+1].text}"

# 4. Nome completo (ex: "doutor João")
for i in range(len(doc)-1):
    if doc[i].text.lower() in ["doutor", "professor", "sr."] and doc[i+1].pos_ == "PROPN":
        nome = f"{doc[i].text} {doc[i+1].text}"

# Resultado final
print("Interpretação da frase:")
print(f"➡ Intenção: {intencao}")
print(f"➡ Pessoa: {nome or nomes_proprios[0]}")
print(f"➡ Data: {data}")
print(f"➡ Hora: {hora}")

"""# Exemplo 2"""

# Instalação de dependências
# !pip install -q spacy
# !python -m spacy download pt_core_news_sm

# Função de interpretação sintática
import spacy

# Carrega modelo de português
nlp = spacy.load("pt_core_news_sm")

def interpretar_frase(frase: str):
    doc = nlp(frase)

    intencao = ""
    nome = ""
    data = ""
    hora = ""

    # 1. Intenção com base no verbo ROOT
    for token in doc:
        if token.dep_ == "ROOT":
            intencao = token.lemma_.lower()  # verbo raiz lematizado

    # 2. Nome próprio
    nomes_proprios = [token.text for token in doc if token.pos_ == "PROPN"]

    for i in range(len(doc)-1):
        if doc[i].text.lower() in ["doutor", "professor", "sr.", "sra."] and doc[i+1].pos_ == "PROPN":
            nome = f"{doc[i].text} {doc[i+1].text}"
            break

    if not nome and nomes_proprios:
        nome = nomes_proprios[0]

    # 3. Data e hora
    for i, token in enumerate(doc):
        if token.text.lower() in ["hoje", "amanhã", "depois"]:
            data = token.text

        if token.like_num and i+1 < len(doc) and doc[i+1].text.lower() == "horas":
            hora = f"{token.text} {doc[i+1].text}"

    # 4. Intenções mapeadas
    mapa_intencoes = {
        "agendar": "agendar_consulta",
        "marcar": "agendar_consulta",
        "cancelar": "cancelar_consulta",
        "remarcar": "remarcar_consulta",
        "gostar": "agendar_consulta",
        "querer": "agendar_consulta",
        "precisar": "agendar_consulta"
    }
    intencao_final = mapa_intencoes.get(intencao, "indefinida")

    return {
        "entrada": frase,
        "intencao": intencao_final,
        "slots": {
            "pessoa": nome,
            "data": data,
            "hora": hora
        },
        "tokens": doc
    }

# Exemplos de teste
entradas = [
    "Gostaria de agendar uma consulta com o doutor João amanhã às 15 horas.",
    "Preciso remarcar com a professora Ana hoje às 10 horas.",
    "Quero cancelar minha consulta com o João.",
    "Agendar reunião com o professor Pedro amanhã.",
    "Gostaria de marcar um horário com a doutora Camila às 9 horas."
]

for frase in entradas:
    resultado = interpretar_frase(frase)
    print("="*70)
    print("Entrada:", resultado["entrada"])
    print("Intenção:", resultado["intencao"])
    print("Slots:", resultado["slots"])
    print(f"{'Token':<15}{'Posição':<10}{'Tipo':<10}{'Dependência':<15}{'Palavra Pai':<15}")
    print("="*70)
    for token in resultado["tokens"]:
        print(f"{token.text:<15}{token.i:<10}{token.pos_:<10}{token.dep_:<15}{token.head.text:<15}")
    print("\n\n")